In [4]:
import numpy as np
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

**Importing DataSet**

In [5]:
data = pd.read_csv('/content/drive/MyDrive/Austin Coursework/Melbourne_Housing.csv')

In [ ]:
data.head()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
0,Airport West,3,t,Nelson,03-09-2016,13.5,3042.0,3.0,2.0,1.0,303.0,225,2016.0,Western Metropolitan,3464,840000
1,Albert Park,2,h,hockingstuart,03-09-2016,3.3,3206.0,2.0,1.0,0.0,120.0,82,1900.0,Southern Metropolitan,3280,1275000
2,Albert Park,2,h,Thomson,03-09-2016,3.3,3206.0,2.0,1.0,0.0,159.0,inf,NaN,Southern Metropolitan,3280,1455000
3,Alphington,4,h,Brace,03-09-2016,6.4,3078.0,3.0,2.0,4.0,853.0,263,1930.0,Northern Metropolitan,2211,2000000
4,Alphington,3,h,Jellis,03-09-2016,6.4,3078.0,3.0,2.0,2.0,208.0,inf,2013.0,Northern Metropolitan,2211,1110000

In [ ]:
data.tail()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
27109,Noble Park,3,h,C21,30-09-2017,22.7,3174.0,3.0,1.0,6.0,569.0,130,1959.0,South-Eastern Metropolitan,11806,627500
27110,Reservoir,3,u,RW,30-09-2017,12.0,3073.0,3.0,1.0,1.0,NaN,105,1990.0,Northern Metropolitan,21650,475000
27111,Roxburgh Park,4,h,Raine,30-09-2017,20.6,3064.0,4.0,2.0,2.0,NaN,225,1995.0,Northern Metropolitan,5833,591000
27112,Springvale South,3,h,Harcourts,30-09-2017,22.2,3172.0,3.0,2.0,1.0,544.0,NaN,NaN,South-Eastern Metropolitan,4054,780500
27113,Westmeadows,4,h,Barry,30-09-2017,16.5,3049.0,4.0,2.0,6.0,813.0,140,1960.0,Northern Metropolitan,2474,791000

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27114 entries, 0 to 27113
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Suburb         27114 non-null  object
 1   Rooms          27114 non-null  int64
 2   Type           27114 non-null  object
 3   SellerG        27114 non-null  object
 4   Date           27114 non-null  object
 5   Distance       27113 non-null  float64
 6   Postcode       27113 non-null  float64
 7   Bedroom        20678 non-null  float64
 8   Bathroom       20672 non-null  float64
 9   Car            20297 non-null  float64
 10  Landsize       17873 non-null  float64
 11  BuildingArea   10543 non-null  object
 12  YearBuilt      11985 non-null  float64
 13  Regionname     27114 non-null  object
 14  Propertycount  27114 non-null  int64
 15  Price          27114 non-null  int64
dtypes: float64(7), int64(3), object(6)
memory usage: 3.3+ MB

In [ ]:
print("number of rows are", data.shape[0], "number of columns", data.shape[1])

number of rows are 27114 number of columns 16

Building area should be a float, Data column needs to be updated to date type from object

In [ ]:
# changing the data type of Date column

#data['Date'] = pd.to_datetime(data['Date'])
#data["Date"].unique()
data['Date'] = pd.to_datetime(data['Date'], format="%d-%m-%Y")

In [ ]:
data['Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 27114 entries, 0 to 27113
Series name: Date
Non-Null Count  Dtype
--------------  -----
27114 non-null  datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 212.0 KB

In [ ]:
#why BuildingArea column has object data type
data['BuildingArea'].unique()

array(['225', '82', 'inf', '263', '242', '251', '117', 'missing', '76',
       '399', '118', '103', '180', '123', '218', '129', '167', '154',
       '275', '121', nan, '125', '255', '75', '156', '240', '268', '108',
       '69', '140', '214', '253', '189', '215', '96', '104', '100', '313',
       '144', '93', '110', '70', '122', '51', '147', '113', '83', '56',
       '137', '85', '64', '175', '3558', '170', '265', '353', '138', '19',
       '116', '87', '74', '320', '300', '210', '120', '86', '97', '200',
       '106', '14', '161', '128', '185', '146', '133', '115', '143',
       '150', '195', '236', '276', '188', '179', '249', '141', '34', '73',
       '107', '84', '81', '207', '50', '264', '312', '235', '221', '183',
       '132', '160', '186', '78', '105', '145', '62', '220', '315', '181',
       '61', '112', '420', '226', '266', '410', '449', '356', '477',
       '250', '95', '190', '284', '247', '213', '209', '119', '111',
       '130', '348', '166', '44', '176', '98', '159', '79', '71', '60',
       '33', '89', '217', '127', '187', '109', '53', '201', '12', '63',
       '223', '102', '254', '327', '16', '165', '65', '139', '134', '280',
       '67', '272', '38', '153', '66', '152', '135', '374', '163', '124',
       '233', '39', '151', '279', '136', '405', '199', '158', '126', '80',
       '57', '36', '142', '77', '435', '92', '149', '114', '349', '178',
       '594', '274', '40', '68', '164', '204', '94', '257', '323', '314',
       '378', '55', '91', '309', '88', '58', '172', '211', '148', '49',
       '52', '174', '191', '335', '808', '168', '203', '520', '212',
       '222', '171', '228', '101', '267', '90', '196', '157', '99', '256',
       '15', '155', '162', '72', '252', '330', '177', '341', '197', '340',
       '182', '245', '270', '42', '229', '232', '131', '297', '237',
       '194', '173', '46', '360', '205', '45', '365', '321', '37', '304',
       '54', '305', '244', '43', '41', '22', '169', '59', '258', '230',
       '287', '618', '792', '355', '202', '395', '351', '325', '248',
       '224', '426', '286', '308', '198', '260', '291', '277', '281',
       '216', '262', '364', '30', '192', '47', '184', '25', '558', '362',
       '375', '347', '241', '475', '413', '400', '101.37', '219', '239',
       '123.21', '140.7481', '86.5', '30.6', '225.5', '322', '409.54',
       '26', '156.6', '227.6', '104.63', '193', '443', '167.13', '148.5',
       '270.18', '53.3', '98.5', '157.9351', '328', '94.3', '21', '310',
       '95.88', '261', '105.7', '72.9', '45.4', '221.3', '113.2',
       '186.75', '540', '127.8', '231', '106.4', '311', '234', '332',
       '206', '259', '246', '296', '269', '306', '380', '302', '48',
       '278', '35', '208', '467', '283', '458', '196.8', '106.2', '32',
       '424', '430', '243', '290', '511', '500', '531', '508', '333',
       '72.3', '66.23', '101.51', '292', '112.9', '99.5', '77.5', '293',
       '105.23', '352', '391', '121.8', '82.6', '136.49', '502', '680',
       '157.9352', '126.8', '100.6', '44.4', '151.54', '20', '397', '495',
       '331', '294', '334', '303', '318', '273', '584', '958', '288',
       '342', '354', '350', '465', '337', '317', '298', '529', '697',
       '289', '602', '6791', '534', '227', '429', '802', '373', '358',
       '238', '316', '393', '180.9', '826.8367', '366', '307', '625',
       '419', '94.5', '392', '28', '116.65', '11', '134.6', '282',
       '183.84', '431', '126.7', '18', '295', '390', '447', '271', '416',
       '370', '660', '463', '361', '496', '324', '173.45', '134.3',
       '464.3', '76.77', '113.76', '107.4', '255.79', '186.36', '490',
       '103.6', '63.7', '106.76', '39.5', '423', '319', '437', '285',
       '453', '472', '418', '487', '31', '301', '116.4', '182.85',
       '109.5', '129.7', '665', '398', '148.47', '553', '182.9', '184.75',
       '193.74', '68.5', '336', '346', '719', '3112', '414', '372', '525',
       '367', '1561', '454', '720', '329', '381', '677', '439', '857',
       '23', '503', '432', '377', '512', '425', '406', '389', '521',
       '6178', '654', '727', '417', '560', '168.01', '306.19', '515.78',
       '196.1', '789', '131.27', '167.87', '183.97', '199.5', '29', '446',
       '75.45', '165.5', '263.5', '585', '516', '345', '27', '444', '427',
       '326', '518', '13', '411', '1022', '339', '461', '376', '513',
       '836', '464', '386', '603', '613', '179.3', '142.6', '147.2',
       '225.98', '113.81', '401', '737', '530', '82.3', '110.87', '450',
       '673', '109.98', '122.25', '105.9', '101.7', '106.9', '93.82',
       '132.6', '154.3', '178.74', '88.3', '80.7', '89.25', '181.6',
       '104.4', '180.56', '123.5', '1143', '506', '575', '859', '653',
       '999', '445', '438', '686', '649', '736', '371.6122', '199.73',
       '118.54', '298.21', '169.5', '42.2', '135.5', '266.76', '272.4',
       '177.8', '139.4', '700', '766', '538', '528', '650', '368', '544',
       '557', '396', '638', '101.76', '363', '634', '195.0964', '470',
       '130.52', '547', '111.04', '63.4', '92.5', '115.96', '121.84',
       '122.86', '114.2', '266.53', '78.54', '85.35', '1041', '607',
       '478', '407', '344', '338', '501', '448', '357', '408', '412',
       '466', '739', '614', '421', '385', '68.11', '153.1', '85.2',
       '93.84', '124.45', '210.68', '200.71', '81.79', '934', '129.92',
       '43.7', '113.6', '66.32', '35.64', '61.6', '388.5', '672'],
      dtype=object)

In [ ]:

#replace inf, missing to NAN
data["BuildingArea"] = data["BuildingArea"].replace(["missing" , "inf"],np.nan)
#data["BuildingArea"].apply(type).value_counts()
data["BuildingArea"].unique()

array(['225', '82', nan, '263', '242', '251', '117', '76', '399', '118',
       '103', '180', '123', '218', '129', '167', '154', '275', '121',
       '125', '255', '75', '156', '240', '268', '108', '69', '140', '214',
       '253', '189', '215', '96', '104', '100', '313', '144', '93', '110',
       '70', '122', '51', '147', '113', '83', '56', '137', '85', '64',
       '175', '3558', '170', '265', '353', '138', '19', '116', '87', '74',
       '320', '300', '210', '120', '86', '97', '200', '106', '14', '161',
       '128', '185', '146', '133', '115', '143', '150', '195', '236',
       '276', '188', '179', '249', '141', '34', '73', '107', '84', '81',
       '207', '50', '264', '312', '235', '221', '183', '132', '160',
       '186', '78', '105', '145', '62', '220', '315', '181', '61', '112',
       '420', '226', '266', '410', '449', '356', '477', '250', '95',
       '190', '284', '247', '213', '209', '119', '111', '130', '348',
       '166', '44', '176', '98', '159', '79', '71', '60', '33', '89',
       '217', '127', '187', '109', '53', '201', '12', '63', '223', '102',
       '254', '327', '16', '165', '65', '139', '134', '280', '67', '272',
       '38', '153', '66', '152', '135', '374', '163', '124', '233', '39',
       '151', '279', '136', '405', '199', '158', '126', '80', '57', '36',
       '142', '77', '435', '92', '149', '114', '349', '178', '594', '274',
       '40', '68', '164', '204', '94', '257', '323', '314', '378', '55',
       '91', '309', '88', '58', '172', '211', '148', '49', '52', '174',
       '191', '335', '808', '168', '203', '520', '212', '222', '171',
       '228', '101', '267', '90', '196', '157', '99', '256', '15', '155',
       '162', '72', '252', '330', '177', '341', '197', '340', '182',
       '245', '270', '42', '229', '232', '131', '297', '237', '194',
       '173', '46', '360', '205', '45', '365', '321', '37', '304', '54',
       '305', '244', '43', '41', '22', '169', '59', '258', '230', '287',
       '618', '792', '355', '202', '395', '351', '325', '248', '224',
       '426', '286', '308', '198', '260', '291', '277', '281', '216',
       '262', '364', '30', '192', '47', '184', '25', '558', '362', '375',
       '347', '241', '475', '413', '400', '101.37', '219', '239',
       '123.21', '140.7481', '86.5', '30.6', '225.5', '322', '409.54',
       '26', '156.6', '227.6', '104.63', '193', '443', '167.13', '148.5',
       '270.18', '53.3', '98.5', '157.9351', '328', '94.3', '21', '310',
       '95.88', '261', '105.7', '72.9', '45.4', '221.3', '113.2',
       '186.75', '540', '127.8', '231', '106.4', '311', '234', '332',
       '206', '259', '246', '296', '269', '306', '380', '302', '48',
       '278', '35', '208', '467', '283', '458', '196.8', '106.2', '32',
       '424', '430', '243', '290', '511', '500', '531', '508', '333',
       '72.3', '66.23', '101.51', '292', '112.9', '99.5', '77.5', '293',
       '105.23', '352', '391', '121.8', '82.6', '136.49', '502', '680',
       '157.9352', '126.8', '100.6', '44.4', '151.54', '20', '397', '495',
       '331', '294', '334', '303', '318', '273', '584', '958', '288',
       '342', '354', '350', '465', '337', '317', '298', '529', '697',
       '289', '602', '6791', '534', '227', '429', '802', '373', '358',
       '238', '316', '393', '180.9', '826.8367', '366', '307', '625',
       '419', '94.5', '392', '28', '116.65', '11', '134.6', '282',
       '183.84', '431', '126.7', '18', '295', '390', '447', '271', '416',
       '370', '660', '463', '361', '496', '324', '173.45', '134.3',
       '464.3', '76.77', '113.76', '107.4', '255.79', '186.36', '490',
       '103.6', '63.7', '106.76', '39.5', '423', '319', '437', '285',
       '453', '472', '418', '487', '31', '301', '116.4', '182.85',
       '109.5', '129.7', '665', '398', '148.47', '553', '182.9', '184.75',
       '193.74', '68.5', '336', '346', '719', '3112', '414', '372', '525',
       '367', '1561', '454', '720', '329', '381', '677', '439', '857',
       '23', '503', '432', '377', '512', '425', '406', '389', '521',
       '6178', '654', '727', '417', '560', '168.01', '306.19', '515.78',
       '196.1', '789', '131.27', '167.87', '183.97', '199.5', '29', '446',
       '75.45', '165.5', '263.5', '585', '516', '345', '27', '444', '427',
       '326', '518', '13', '411', '1022', '339', '461', '376', '513',
       '836', '464', '386', '603', '613', '179.3', '142.6', '147.2',
       '225.98', '113.81', '401', '737', '530', '82.3', '110.87', '450',
       '673', '109.98', '122.25', '105.9', '101.7', '106.9', '93.82',
       '132.6', '154.3', '178.74', '88.3', '80.7', '89.25', '181.6',
       '104.4', '180.56', '123.5', '1143', '506', '575', '859', '653',
       '999', '445', '438', '686', '649', '736', '371.6122', '199.73',
       '118.54', '298.21', '169.5', '42.2', '135.5', '266.76', '272.4',
       '177.8', '139.4', '700', '766', '538', '528', '650', '368', '544',
       '557', '396', '638', '101.76', '363', '634', '195.0964', '470',
       '130.52', '547', '111.04', '63.4', '92.5', '115.96', '121.84',
       '122.86', '114.2', '266.53', '78.54', '85.35', '1041', '607',
       '478', '407', '344', '338', '501', '448', '357', '408', '412',
       '466', '739', '614', '421', '385', '68.11', '153.1', '85.2',
       '93.84', '124.45', '210.68', '200.71', '81.79', '934', '129.92',
       '43.7', '113.6', '66.32', '35.64', '61.6', '388.5', '672'],
      dtype=object)

In [10]:
#convert BuildingArea to Float
data["BuildingArea"] =  data["BuildingArea"].astype(float)
data["BuildingArea"].apply(type).value_counts()

ValueError: could not convert string to float: 'missing'

In [6]:
data.isnull().sum()

Suburb               0
Rooms                0
Type                 0
SellerG              0
Date                 0
Distance             1
Postcode             1
Bedroom           6436
Bathroom          6442
Car               6817
Landsize          9241
BuildingArea     16571
YearBuilt        15129
Regionname           0
Propertycount        0
Price                0
dtype: int64

In [7]:
data.duplicated().sum()

np.int64(11)

In [8]:
data.drop_duplicates(inplace=True)
data.reset_index(drop = True ,inplace = True )

In [9]:
data.tail()

,Suburb,Rooms,Type,SellerG,Date,Distance,Postcode,Bedroom,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Regionname,Propertycount,Price
27098,Noble Park,3,h,C21,30-09-2017,22.7,3174.0,3.0,1.0,6.0,569.0,130,1959.0,South-Eastern Metropolitan,11806,627500
27099,Reservoir,3,u,RW,30-09-2017,12.0,3073.0,3.0,1.0,1.0,NaN,105,1990.0,Northern Metropolitan,21650,475000
27100,Roxburgh Park,4,h,Raine,30-09-2017,20.6,3064.0,4.0,2.0,2.0,NaN,225,1995.0,Northern Metropolitan,5833,591000
27101,Springvale South,3,h,Harcourts,30-09-2017,22.2,3172.0,3.0,2.0,1.0,544.0,NaN,NaN,South-Eastern Metropolitan,4054,780500
27102,Westmeadows,4,h,Barry,30-09-2017,16.5,3049.0,4.0,2.0,6.0,813.0,140,1960.0,Northern Metropolitan,2474,791000